name: game_audios
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter
  clock: ^1.1.0
  flame_audio: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter_gen:
  line_length: 120
  assets:
    package_parameter_enabled: true

flutter:
  assets:
    - assets/sfx
    - assets/music
